
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnvhsnrxtitqhxjjljpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudmhzbnJ4dGl0cWh4ampsanBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTE1OTksImV4cCI6MjA1ODA2NzU5OX0.0ckuZqGPsJgtkvz_WtDLFL0lmGyGGWIkjPnPTAWUm-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
